[greenclip]
    blacklisted_applications = []

    enable_image_support = true
    image_cache_directory = "/tmp/greenclip"

    history_file = "~/.cache/greenclip.history"
    max_history_length = 50
    static_history = []

    max_selection_size_bytes = 0
    trim_space_from_selection = true
    use_primary_selection_as_input = false
